features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: ''
favicon:
  use_default: false
  path: themes/custom/aaslp_lib_unb_ca/favicon.png
  mimetype: image/png
